import streamlit as st
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForTokenClassification
#read pdf
import PyPDF2
txt = st.text_area("NDA No. 48343/2023
48343-2023-Technip Energies France SAS- SAPURA-13042023.DocxPage 1 of 4
NON-DISCLOSURE AGREEMENT
This Agreement is effective as of 13th April,2023 (“Effective Date”), by and between Technip Energies France SAS, a corporation organized under the laws of -France, having its principal place of business at 2126 boulevard de la Défense - Immeuble ORIGINE - CS 10266 - 92741 Nanterre CEDEX France (“Technip Energies”) and Sapura Fabrication Sdn.Bhd., Malaysia having its principal place of business at N° 7, Jalan Tasik, Mines Resort City, 43300 Seri Kembangan, Selangor., Malaysia (“Company”) being Technip Energies interested in disclosing selected information to Company for Engaging in a business relationship, including, but not limited to, quotation preparation, procurement/supply of goods and/or services, etc. with respect to AO6 Floater fabrication (the “Disclosure Purpose”).
WHEREAS, Technip Energies may disclose valuable information to the Company and certain information so disclosed may be confidential. Accordingly, the Parties agree to the following terms and conditions:
1. Definition: Confidential Information. “Confidential Information” is defined as any information transmitted orally and/or in writing or other physical or electronic media, software or information in any format, disclosed to Company by Technip Energies relating to the Disclosure Purpose, which would be understood by a reasonable person to be considered as confidential, whether or not such information is marked as “confidential” at the time of disclosure. Any item, written information, software or electronic media may be brought within the scope of this Agreement by an accompanying letter to the receiving party identifying the particular item, written information, software or electronic media and claiming confidentiality with respect thereto. Confidential Information may include, without limitation: (a) proprietary financial, commercial and technical information disclosed by Technip Energies Party to the Company in connection with the performance of the Disclosure Purpose concerning Technip Energies and/or its activities; (b) the identity of or other pertinent information with respect to the actual or potential customers or customer contacts and customer sales strategies; (c) trade secrets, know-how, designs, methods, practices, procedures, processes and formulas with respect to manufacturing, assembly, installation, design, or processing the products and any component or part thereof; (d) sources of supply for products, components and services; (e) any other secret processes, formulas and methods (f) photographs of equipment owned by Technip Energies and/or located at Technip Energies’s facilities; (g) any information acquired from the observation of Company, its agents or consultants in the office or other locations of Technip Energies in relation to the Disclosure Purpose or the business of Technip Energies; (h) this Agreement and its existence, as well as the nature and stage of the negotiations between the Parties; (i) any reports, analyses, compilations, studies or other documents prepared by Technip Energies, on behalf of or for Company which contain, derive from or otherwise reflect any information described in (a) to (i) above.
2. Enforcement: All provisions of this Agreement shall also be applied to the Affiliates of the Parties. For the purposes of this Agreement, “Affiliate” of a Party shall mean any entity which, directly or indirectly, controls or is controlled by, or is under common control with, that Party, where control is (a) the possession, directly or indirectly, of the power to direct or cause the direction of the management or operating policies of the entity through the exercise of voting rights, contract, trust or otherwise, or (b) a right to appoint the majority of the directors of the entity, and “Affiliates” means any two or more of them.
3. Nondisclosure and Restriction on Use. The Company agrees to retain Confidential Information in confidence for a period of six (06) years from the expiry or termination of this Agreement and to exercise reasonable precautions to prevent unauthorized disclosure of the received Confidential Information to any third party, in whole or in part, and not to use the Confidential Information for any purpose other than in furtherance of the Disclosure Purpose,
NDA No. 48343/2023
48343-2023-Technip Energies France SAS- SAPURA-13042023.DocxPage 2 of 4
including the competition with Technip Energies in any of its business. Company will not reverse engineer, decompile, disassemble, modify, adapt, or create derivative works of the Confidential Information, or intentionally allow third parties to do so. Company will not disclose the Confidential Information either in whole or in part, to any third party without the prior written consent of Technip Energies. If Company is authorized to disclose, it shall be a condition of such disclosure that prior to any disclosure, the third party enters into an appropriate agreement with Company, whereby the terms of this Agreement shall be respected and agreed upon by said third party. In the event of loss or theft of any documents, items of work in progress, or any work products embodying Confidential Information by or from any party, Technip Energies must be notified immediately.
4. Reproduction of Confidential Information. The Company shall not reproduce copies of the Confidential Information (including using electronic means, such as screen captures) unless such duplication is a reasonable requirement for furtherance of the Disclosure Purpose.
5. Disclosure of Confidential Information. The Company shall limit dissemination of Technip Energies’s Confidential Information to such of its and its Affiliates´ employees, officers, directors, agents, consultants, contractors and/or contract employees or representatives who have a need to know in furtherance of the Disclosure Purpose. All persons to whom disclosure of the Confidential Information is made shall either sign a written acknowledgement and acceptance of the confidentiality obligations imposed upon Company hereunder or a written confidentiality agreement with Company which provides at least as strict confidentiality obligations upon such persons to provide the same protection of Technip Energies’s Confidential Information as are imposed upon the Company. Company shall be responsible for compliance with the provisions of this Agreement.
6. Exceptions to Nondisclosure. The Company shall not be subject to the obligations of this Agreement with respect to Confidential Information which:
(a) is or becomes known publicly through no wrongful act of the Company; or
(b) was already known to the Company at the time of disclosure hereunder as shown by the Company’s prior written records; or
(c) is learned by the Company from a third party under no obligation to Technip Energies; or
(d) is independently developed by an employee, agent, or consultant of the Company with no knowledge of disclosures hereunder, or
(e) is approved for release by written authorization of Technip Energies.
7. No License or Right. No right or license, whether expressed or implied, in the Confidential Information is granted to the Company other than to use the Confidential Information in the manner and to the extent authorized by this Agreement. Company agrees that Confidential information is and shall at all times remain and/or be deemed to remain proprietary to Technip Energies who is and shall be the sole owner of the rights of industrial or intellectual property relating thereto as, without limitation, patents, trademarks, design, patterns, methodologies, know-how, copyrights and other protected rights.
8. Warranties. Technip Energies makes no representations or warranties, express or implied, as to the quality, accuracy and/or completeness of the Confidential Information disclosed hereunder. Company agrees that Technip Energies shall have no liability whatsoever with respect to the use of or reliance upon the Confidential Information by Company.
NDA No. 48343/2023
48343-2023-Technip Energies France SAS- SAPURA-13042023.DocxPage 3 of 4
9. Return or Destruction of Confidential Information. Company agrees to promptly return to Technip Energies or destroy, upon written request, all Confidential Information and all copies and notes thereon, regardless of the form of storage or retrieval and to certify, in writing that all Confidential Information and copies and notes thereon have been returned or destroyed. One or more electronic copies of the Confidential Information may be retained if the same is routinely captured in disaster recovery back-up systems.
10. Confidential Information Exchange. No Confidential Information shall be exchanged after the expiration of this Agreement, after the Parties abandon the Disclosure Purpose or any time after prior written notice is given by one Party to the other that the notifying party does not wish to receive or disclose any further Confidential Information, whichever occurs earlier.
11. Publicity. No information, release or public announcement or confirmation or denial of this Agreement will be made without prior coordination and the express written approval of the other Party.
12. Non-Exclusivity. This agreement does not limit or restrict the parties’ ability to engage in their respective businesses, nor does it prevent either party from pursuing similar discussions or transactions with third parties.
13. Costs and Fees. Unless otherwise agreed in writing, each party shall bear its own costs and expenses in connection with the Disclosure Purpose.
14. Assignment. Neither Party may assign or transfer its rights or obligations under this Agreement without the prior written consent of the other party. Any attempted assignment or transfer without such prior written consent will be void.
15. Legally compelled disclosure. In the event, Company becomes legally compelled (by deposition, interrogatory, request for documents, order, subpoena, civil investigative demand or similar process issued by a court of competent jurisdiction or by a government body) to disclose any of the Confidential Information, prompt prior written notice of any such requirement shall be provided to Technip Energies so that Technip Energies may seek a protective order or other appropriate remedy and/or waive compliance with the terms of this Agreement. In the event, such protective order or other remedy is not obtained, and irrespective of whether compliance with the provisions hereof is waived, the Company shall cause to be disclosed only that portion of the Confidential Information which in the opinion of Company’s legal counsel, Company is compelled to disclose.
16. Equitable Remedy. The parties each recognize that a breach of this Agreement may cause irreparable harm to the other party and that actual damages may be difficult to ascertain and, in any event, may be inadequate. Accordingly, the parties agree that in the event of such breach, the injured party may be entitled to injunctive relief in addition to such other legal or equitable remedies as may be available.
17. Controlling Law. This Agreement shall be governed and interpreted in accordance with the laws of France without reference to their respective conflicts of law principles. In the event of any dispute, or difference arising out of, or relating to this Agreement, or the breach thereof, the parties shall to settle their dispute in Tribunal de Commerce de Nanterre, France.
18. Trade Control Compliance. The Parties acknowledge that the disclosure of Confidential Information under this Agreement may be subject to governmental laws, regulations, decrees and orders issued by (i) the United Nations, (ii) the United States of America, (iii) the European Union or any of its Member States, (iv) the United Kingdom or any other jurisdiction relevant to this Agreement that may directly or indirectly sanction, prohibit or restrict certain activities
NDA No. 48343/2023
48343-2023-Technip Energies France SAS- SAPURA-13042023.DocxPage 4 of 4
including, but not limited to, (i) import, export, re-export, transfer, or trans-shipment of goods, services, technology, or software and/or (ii) financing of, investment in, or direct or indirect transactions or dealings with certain countries, territories, regions, governments, projects, or specifically designated persons or entities (“Trade Control Laws”). The Parties agree to comply with and shall not knowingly breach or cause another Party to breach, any applicable Trade Control Laws in connection with Confidential Information supplied under this Agreement. The Parties shall not be liable to any other party for any inability to supply Confidential Information in connection with this Agreement as a result of its compliance with applicable Trade Control Laws. This clause shall survive the termination or expiry of this Agreement.
19. Term. This Agreement shall remain in force for a period of five (05) years from the Effective Date. However, the obligations of non-disclosure and non-use shall extend beyond the expiration or termination of this Agreement for the period specified in paragraph 3, above.
20. Counterparts. This Agreement may be executed in any number of counterparts and by the parties hereto in separate counterparts, each of which when so executed shall be deemed to be an original and all of which taken together shall constitute one and the same agreement.
21. Entire Agreement. This Agreement contains the entire and complete agreement between the Parties, and supersedes any and all prior understandings, promises, representations, and agreements, oral or written, with respect to the Disclosure Purpose. No modification, change, or waiver of this Agreement shall be valid unless made in writing and signed by authorized representatives of the Parties. This Agreement does not obligate the Parties to enter into negotiations or any subsequent agreement.
IN WITNESS WHEREOF, the parties have caused this Agreement to be executed by their duly authorized representatives as of the date last signed below.
FOR Technip Energies: FOR Company:
______________________________ ______________________________
(signature) (signature)
By: __________________________ By: ___________________________
Title: ________________________ Title: _________________________
Dated: ________________________ Dated: ________________________")

def read_pdf(file):
    pdf_reader = PyPDF2.PdfReader(file)
    text = ""
    for page in pdf_reader.pages:
        text += " "
        text += page.extract_text()
    return text

#file="./48343-2023-Technip Energies France SAS- SAPURA-13042023.pdf"
#text=read_pdf(file)
#print(text)
tokenizer = AutoTokenizer.from_pretrained("harshildarji/gbert-legal-ner", use_auth_token="AUTH_TOKEN")
model = AutoModelForTokenClassification.from_pretrained("harshildarji/gbert-legal-ner", use_auth_token="AUTH_TOKEN")

ner = pipeline("ner", model=model, tokenizer=tokenizer)
example = txt
results = ner(example)
st.write(results)
